### ISSUE TITLE
CP search fail with noneType error

### ISSUE THREAD

**Issue by Benvii** [OpenPathView/OPV_Tasks#54]
I've got the following error, it might comes from the lazyness of the client.

```
Traceback (most recent call last):
  File "/home/opv/venvs/opv/bin/opv-task", line 11, in <module>
    sys.exit(main())
  File "/home/opv/venvs/opv/lib/python3.5/site-packages/opv_tasks/__main__.py", line 57, in main
    lastTaskReturn = run(dir_manager_client, db_client, task_name, inputData)
  File "/home/opv/venvs/opv/lib/python3.5/site-packages/opv_tasks/__main__.py", line 73, in run
    return task.run(options=inputData)
  File "/home/opv/venvs/opv/lib/python3.5/site-packages/opv_tasks/task/task.py", line 94, in run
    taskOutput = self.runWithExceptions(options=options)
  File "/home/opv/venvs/opv/lib/python3.5/site-packages/opv_tasks/task/makealltask.py", line 58, in runWithExceptions
    lastTaskReturn = runTask(self._opv_directory_manager, self._client_requestor, "findnearestcp", cp.lot.id)
  File "/home/opv/venvs/opv/lib/python3.5/site-packages/opv_tasks/utils.py", line 49, in runTask
    return task.run(options=inputData)
  File "/home/opv/venvs/opv/lib/python3.5/site-packages/opv_tasks/task/task.py", line 94, in run
    taskOutput = self.runWithExceptions(options=options)
  File "/home/opv/venvs/opv/lib/python3.5/site-packages/opv_tasks/task/findnearestcptask.py", line 151, in runWithExceptions
    cps = self.searchNearestLocatedCp(lot=lot)
  File "/home/opv/venvs/opv/lib/python3.5/site-packages/opv_tasks/task/findnearestcptask.py", line 102, in searchNearestLocatedCp
    if not(s.lot.id_lot == lot.id_lot and s.lot.id_malette == lot.id_malette):
AttributeError: 'NoneType' object has no attribute 'id_lot'

```

To reproduce it on our cluster : 
```
opv-task makeall '{"id_lot":8737, "id_malette":42}' --debug
```

**Comment by Benvii** [comment]
Problem comes from the reconstructed sensors that aren't linked to a lot but linked to a panorama.

Here the buggy sensor is **14405-42**.
```sql
SELECT COUNT(*) from panorama WHERE id_sensors_reconstructed=14405;
 count 
-------
     1
```

When panorama is present we should use it, I'm going to update it.
